import { getSession } from '@/lib/auth/session';
import { anthropicConfigured, config, supabaseConfigured } from '@/lib/config';
import { describeMediaProviders, simulationAllowed } from '@/lib/integrations/providers/registry';
import { INTEGRATION_DEFINITIONS, resolveIntegrations } from '@/lib/integrations/registry';
import { Badge, Panel } from '@/components/ui';
import { PageShell, Section } from '@/components/layout/PageShell';
import { SETTINGS_TABS } from '@/components/settings/tabs';

export const dynamic = 'force-dynamic';

type State = 'connected' | 'simulated' | 'missing' | 'demo';

const TONE: Record<State, 'emerald' | 'amber' | 'red' | 'neutral'> = {
  connected: 'emerald',
  simulated: 'amber',
  missing: 'red',
  demo: 'amber',
};

/**
 * What this instance actually is, right now.
 *
 * Command Centre behaves genuinely differently without Supabase — no accounts,
 * in-memory storage, simulated media — and that difference is invisible from
 * the interface itself. This page states it plainly, in one place, so "why is
 * my data gone" and "why is this public" are answerable in ten seconds.
 */
export default async function SystemStatusPage() {
  const { isDemo } = await getSession();
  const providers = describeMediaProviders();
  const integrations = resolveIntegrations(INTEGRATION_DEFINITIONS);

  const youtube = integrations.find((item) => item.kind === 'youtube');
  const renderer = providers.find((item) => item.kind === 'renderer');
  const voice = providers.find((item) => item.kind === 'voice');
  const image = providers.find((item) => item.kind === 'image');
  const video = providers.find((item) => item.kind === 'video');
  const stock = providers.find((item) => item.kind === 'stock');

  const providerState = (descriptor: (typeof providers)[number] | undefined): State =>
    !descriptor ? 'missing' : descriptor.simulated ? 'simulated' : descriptor.connected ? 'connected' : 'missing';

  const rows: { label: string; state: State; value: string; detail: string }[] = [
    {
      label: 'Storage',
      state: supabaseConfigured ? 'connected' : 'demo',
      value: supabaseConfigured ? 'Supabase (Postgres)' : 'In-memory (demo)',
      detail: supabaseConfigured
        ? 'Row Level Security is on for every table. Queries run as your user.'
        : 'Data lives in this server process and is reseeded on restart. Nothing is persisted.',
    },
    {
      label: 'Authentication',
      state: supabaseConfigured ? 'connected' : 'demo',
      value: supabaseConfigured ? 'Enabled' : 'Demo — public',
      detail: supabaseConfigured
        ? 'Unauthenticated pages redirect to sign-in; API routes return 401.'
        : 'There are no accounts. Anyone who can reach this URL can read this workspace.',
    },
    {
      label: 'AI',
      state: anthropicConfigured ? 'connected' : 'simulated',
      value: anthropicConfigured ? `Connected · ${config.anthropic.model}` : 'Simulated',
      detail: anthropicConfigured
        ? 'Agents call a real model and every run is costed from real token counts.'
        : 'Agents run on a simulated provider that produces schema-valid output prefixed [Simulated]. The pipeline is real; the text is not.',
    },
    {
      label: 'Renderer',
      state: providerState(renderer),
      value: renderer?.name ?? 'Local ffmpeg',
      detail: 'Video assembly runs locally on this server. No third-party render service, no spend.',
    },
    {
      label: 'Voice',
      state: providerState(voice),
      value: voice?.simulated ? 'Simulated' : voice?.connected ? voice.name : 'Not connected',
      detail: voice?.connected
        ? 'Narration is generated by a real provider.'
        : voice?.simulated
          ? 'Demo Mode placeholder narration, always badged Simulated.'
          : 'Missions stop at the narration step and say which variables are needed.',
    },
    {
      label: 'Image',
      state: providerState(image),
      value: image?.simulated ? 'Simulated' : image?.connected ? image.name : 'Not connected',
      detail: image?.connected
        ? 'Scene stills and thumbnails come from a real provider.'
        : 'Missions stop at asset generation rather than faking imagery.',
    },
    {
      label: 'Video',
      state: providerState(video),
      value: video?.simulated ? 'Simulated' : video?.connected ? video.name : 'Not connected',
      detail: 'Generated motion clips. Optional — most scenes do not need them.',
    },
    {
      label: 'Stock',
      state: providerState(stock),
      value: stock?.simulated ? 'Simulated' : stock?.connected ? stock.name : 'Not connected',
      detail: 'Licensed footage and stills. Nothing scrapes copyrighted media.',
    },
    {
      label: 'YouTube',
      state: youtube?.connected ? 'connected' : 'missing',
      value: youtube?.connected ? 'Connected' : 'Not connected',
      detail: youtube?.connected
        ? 'Live channel analytics and uploads via the official Data API.'
        : 'Analytics screens show only recorded data, and nothing can be published.',
    },
  ];

  return (
    <PageShell
      title="System status"
      description="What this instance actually is. Command Centre behaves differently without Supabase, and this says how."
      tabs={SETTINGS_TABS}
      wide
    >
      {isDemo && (
        <Panel className="mb-4 border-amber-500/25 bg-amber-500/[0.07] p-4">
          <p className="text-[12px] leading-relaxed text-amber-100/80">
            <strong className="font-semibold">This instance has no database and no accounts.</strong>{' '}
            That is correct for local development and wrong for a public deployment. Configure
            Supabase, run the three migrations, and create your owner account before putting this
            anywhere reachable.
          </p>
        </Panel>
      )}

      <Section title="Services">
        <Panel className="overflow-hidden">
          <ul className="divide-y divide-[var(--color-edge-soft)]">
            {rows.map((row) => (
              <li key={row.label} className="flex flex-wrap items-start gap-x-3 gap-y-1 px-4 py-3">
                <span className="w-[110px] shrink-0 text-[13px] font-medium">{row.label}</span>
                <Badge tone={TONE[row.state]}>{row.value}</Badge>
                <span className="min-w-0 flex-1 basis-full text-[12px] leading-relaxed text-[var(--color-ink-muted)] sm:basis-0">
                  {row.detail}
                </span>
              </li>
            ))}
          </ul>
        </Panel>
      </Section>

      <Section title="Simulation">
        <Panel className="p-4">
          <p className="text-[13px] leading-relaxed text-[var(--color-ink-muted)]">
            {simulationAllowed()
              ? 'Simulated media is on. Missing providers stand in with placeholder assets that are stored with simulated: true, badged throughout, and never given a public URL. Set DISABLE_SIMULATED_MEDIA=true to make those steps stop instead.'
              : 'Simulated media is off. A missing provider stops the mission and names what it needs. Nothing is ever faked.'}
          </p>
        </Panel>
      </Section>
    </PageShell>
  );
}
